Rails.application.routes.draw do
  root 'welcome#index'
  get '/audiobible' => 'pages#audiobible'
  get '/biblememory' => 'pages#biblememory'
  get '/churchdirectory' => 'pages#churchdirectory'
  get '/doctrinalstatement' => 'pages#doctrinalstatement'
  get '/events' => 'pages#events'
  get '/location' => 'location#location'
  get '/malawi' => 'pages#malawi'
  get '/ourpastor' => 'pages#ourpastor'
  get '/preaching' => 'preaching#show'
  get '/privacypolicy' => 'pages#preaching'
  get '/psalms' => 'pages#psalms'
  get '/radio' => 'pages#radio'
  get '/service' => 'pages#service'
  get '/soulwinning' => 'pages#soulwinning'
  get '/termsandconditions' => 'pages#termsandconditions'
end
